// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jsontotree.actions;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.JsonNodeType;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import jsontotree.Misc;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ConvertJSONToRootTree extends CustomJavaAction<IMendixObject>
{
	private java.lang.String JSON;
	private java.lang.String childKey;

	public ConvertJSONToRootTree(IContext context, java.lang.String JSON, java.lang.String childKey)
	{
		super(context);
		this.JSON = JSON;
		this.childKey = childKey;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext ctx = this.getContext();
		
		if (this.JSON == "" || this.JSON == null) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("JSON is empty");
		}
		
		ObjectMapper mapper = new ObjectMapper();
		JsonNode rootNode = mapper.readTree(this.JSON);
		
		if (rootNode.getNodeType() != JsonNodeType.ARRAY) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("JSON is not an array!");
		}
		
		IMendixObject result = Core.instantiate(ctx, jsontotree.proxies.Root.getType());
		
		Misc.traverseRootObjects(ctx, result, rootNode, this.childKey);
		
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ConvertJSONToRootTree";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
